import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { LuGraduationCap } from "react-icons/lu";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Career",
    hash: "#career",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    type: "work",
    title: "Software Development Engineer",
    company: "Chainscore Labs",
    location: "Pune, India",
    description:
      "Joined in July 2024 as an intern and 3 month later transitioned to full-time SDE. Work spans the full stack and a few layers below it - from real-time trading UIs to protocol-level SDKs. Currently focused on systems where correctness, performance, and concurrency actually matter.",
    icon: React.createElement(CgWorkAlt),
    date: "Jul 2024 - Present",
    current: true,
    highlights: [
      "Built a responsive, feature-rich UI for a staking, casino, and sports betting platform using React, TypeScript, Redux Toolkit, and GSAP, integrating crypto wallets with Wagmi and RainbowKit for seamless user onboarding.",
      "Engineered a real-time notification system using Server-Sent Events (SSE), enabling low-latency live updates across enterprise workflows.",
      "Developed Node.js / Express APIs with WebSocket services for real-time data, transaction handling, and secure wallet deposit / withdrawal flows, supporting thousands of concurrent users.",
      "Co-developing JAM (Join-Accumulate Machine) - Polkadot's next-gen protocol from Gavin Wood.",
      "Contributing to a high-performance SDK in C with QUIC / TLS 1.3 networking - designed for 1,000+ validators at sub-2s latency.",
      "Architecting computational pipelines and consensus mechanisms in Python: off-chain auditing, dispute resolution, work-report distribution, adaptive tranche logic.",
      "Shipped 20k+ LOC to TelosX, a Layer-1 crypto exchange - trading frontends in Next.js + TypeScript with real-time WebSocket feeds, ~40% UI perf improvement for 10k+ users.",
      "Built Node.js / Express APIs with WebSocket services supporting thousands of concurrent users.",
    ],
    skills: [
      "C",
      "Python",
      "TypeScript",
      "Next.js",
      "Node.js",
      "QUIC",
      "TLS 1.3",
      "WebSockets",
      "Polkadot",
      "Redux",
    ],
  },
  {
    type: "work",
    title: "Full Stack Engineering Intern",
    company: "Elevatifier",
    location: "Remote",
    description:
      "Owned backend-heavy slices of a recruiter platform - REST API design, MongoDB modeling, and end-to-end feature delivery alongside the frontend team.",
    icon: React.createElement(CgWorkAlt),
    date: "Mar 2024 - May 2024",
    highlights: [
      "Designed and shipped REST APIs in Node.js + Express, integrated with the React / Next.js frontend.",
      "Optimized MongoDB queries and indexing - meaningful response-time reductions on hot paths.",
      "Implemented validation, error handling, and auth flows across the stack.",
    ],
    skills: [
      "Node.js",
      "Express",
      "MongoDB",
      "React",
      "Next.js",
      "TypeScript",
      "Git",
      "Postman",
    ],
  },
  {
    type: "education",
    title: "B.Tech, Information Technology",
    company: "Kamla Nehru Institute of Technology (KNIT)",
    location: "Sultanpur, India",
    description:
      "Graduated with CGPA 8.4. Strong foundation in computer systems, networks, and software engineering - paired with hands-on full-stack and DSA work that became the launching pad for everything since.",
    icon: React.createElement(LuGraduationCap),
    date: "Nov 2020 - Jul 2024",
    highlights: [
      "Core CS coursework: DSA, OS, DBMS, Computer Networks, OOP.",
      "Multiple side projects across the MERN / Next.js stack.",
      "Active in competitive programming - 350+ problems solved on LeetCode.",
    ],
    skills: ["C++", "DSA", "DBMS", "OS", "Computer Networks", "OOP", "SQL"],
  },
] as const;

export const skillsData = [
  "TypeScript",
  "JavaScript",
  "C",
  "C++",
  "Python",
  "Rust",
  "Go",
  "React",
  "Next.js",
  "Redux",
  "Redux Toolkit",
  "Node.js",
  "Express",
  "NestJS",
  "FastAPI",
  "GSAP",
  "Framer Motion",
  "Tailwind CSS",
  "DaisyUI",
  "Material UI",
  "React Router",
  "Vite",
  "HTML",
  "CSS",
  "MongoDB",
  "PostgreSQL",
  "NeonDB",
  "Supabase",
  "Prisma",
  "Google Firebase",
  "QUIC Protocol",
  "WebSockets",
  "aioquic",
  "Ed25519",
  "Blockchain",
  "Polkadot",
  "Web3",
  "Wagmi",
  "RainbowKit",
  "Auth0",
  "Clerk",
  "JWT",
  "Razorpay",
  "Cloudinary",
  "OpenAI",
  "AI",
  "Jest",
  "Git",
  "GitHub",
  "Docker",
  "Linux",
  "Postman",
  "Figma",
  "AWS",
  "AWS EC2",
  "Azure",
  "Vercel",
] as const;
