import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { LuGraduationCap } from "react-icons/lu";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Career",
    hash: "#career",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    type: "work",
    title: "Software Development Engineer",
    company: "Chainscore Labs",
    location: "Pune, India",
    description:
      "Joined Chainscore Labs in July 2024 as a Software Development Engineer, working across the full stack and a few layers below it - from real-time trading UIs to protocol-level SDKs. Currently focused on systems where correctness, performance, and concurrency are critical.",
    icon: React.createElement(CgWorkAlt),
    date: "Jul 2024 - Present",
    current: true,
    highlightGroups: [
      {
        label: "Frontend & Product",
        items: [
          "Built a responsive, feature-rich UI for a large-scale staking, casino, and sports-betting platform using React, TypeScript, Redux Toolkit, and GSAP - integrating crypto wallets via Wagmi and RainbowKit for seamless onboarding.",
          "Architected Redux Toolkit state management across the platform: 41 feature slices, 55+ typed async thunks, centralized error handling, and persistent auth/wallet/settings state.",
          "Built the TelosX (Layer-1 blockchain exchange) trading frontend using Next.js and TypeScript - landing page, Auth0 authentication, and crypto swap/spot-margin trading UI powered by real-time Binance API data. Shipped 20k+ LOC and improved UI latency by 40% for 10,000+ users.",
        ],
      },
      {
        label: "Backend & Real-Time Systems",
        items: [
          "Developed Node.js/Express APIs with WebSocket services for real-time data, transaction handling, and secure wallet deposit/withdrawal flows, supporting thousands of concurrent users.",
          "Built a real-time notification system using Server-Sent Events (SSE) for low-latency live updates across enterprise workflows.",
          "Built a real-time gaming leaderboard system with Redis caching for leaderboards, odds, and game-state data - reducing database load and improving response times for high-traffic, read-heavy requests.",
          "Developed Golang-based data-layer services using Kafka and ClickHouse to process high-volume trading events, routing market/order data to persistent storage and data-warehouse systems for real-time analytics and historical reporting.",
        ],
      },
      {
        label: "Protocol & Systems Engineering (Polkadot JAM)",
        items: [
          "Co-developing JAM (Join-Accumulate Machine), Polkadot's next-generation decentralized compute protocol introduced by Gavin Wood.",
          "Architecting computational pipelines and consensus mechanisms in Python - off-chain auditing, dispute resolution, work-report distribution, and adaptive tranche logic.",
          "Contributing to a high-performance SDK in C and Golang with QUIC/TLS 1.3 networking, designed to scale to 1,000+ validators at sub-2-second latency.",
        ],
      },
    ],
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Redux",
      "Node.js",
      "NestJS",
      "React Native",
      "PostgreSQL",
      "Redis",
      "gRPC",
      "Docker",
      "AWS EC2",
      "CI/CD",
      "Golang",
      "C/C++",
      "QUIC",
      "TLS 1.3",
      "WebSockets",
      "Polkadot",
      "Python",
    ],
  },
  {
    type: "work",
    title: "Full Stack Developer",
    company: "Elevatifier",
    location: "Remote",
    description:
      "Owned backend-heavy slices of the platform end to end - REST API design, MongoDB modeling, and feature delivery alongside the frontend team.",
    icon: React.createElement(CgWorkAlt),
    date: "Apr 2024 - Jun 2024",
    highlights: [
      "Designed and shipped REST APIs in Node.js/Express, integrated with a React/Next.js frontend.",
      "Built a role-based admin UI in React.js for managing courses, users, and enrollments.",
      "Optimized MongoDB queries and indexing, meaningfully reducing response times on hot paths.",
      "Implemented validation, error handling, and authentication flows across the stack.",
      "Implemented end-to-end video upload and streaming with AWS S3, optimizing playback for concurrent student access.",
      "Integrated Razorpay course payments with webhook handling for payment confirmation.",
    ],
    skills: [
      "Node.js",
      "Express",
      "MongoDB",
      "React",
      "Next.js",
      "TypeScript",
      "AWS S3",
      "Razorpay",
      "Git",
      "Postman",
    ],
  },
  {
    type: "education",
    title: "B.Tech, Information Technology",
    company: "Kamla Nehru Institute of Technology (KNIT)",
    location: "Sultanpur, India",
    description:
      "Graduated with CGPA 8.4. Strong foundation in computer systems, networks, and software engineering - paired with hands-on full-stack and DSA work that became the launching pad for everything since.",
    icon: React.createElement(LuGraduationCap),
    date: "Nov 2020 - Jul 2024",
    highlights: [
      "Core CS coursework: DSA, OS, DBMS, Computer Networks, OOP.",
      "Multiple side projects across the MERN / Next.js stack.",
      "Active in competitive programming - 450+ problems solved on LeetCode.",
    ],
    skills: ["C++", "DSA", "DBMS", "OS", "Computer Networks", "OOP", "SQL"],
  },
] as const;

export const skillsData = [
  "TypeScript",
  "JavaScript",
  "C",
  "C++",
  "Python",
  "Rust",
  "Go",
  "React",
  "Next.js",
  "Redux",
  "Redux Toolkit",
  "Node.js",
  "Express",
  "NestJS",
  "FastAPI",
  "GSAP",
  "Framer Motion",
  "Tailwind CSS",
  "DaisyUI",
  "Material UI",
  "React Router",
  "Vite",
  "HTML",
  "CSS",
  "MongoDB",
  "PostgreSQL",
  "NeonDB",
  "Supabase",
  "Prisma",
  "Google Firebase",
  "QUIC Protocol",
  "WebSockets",
  "aioquic",
  "Ed25519",
  "Blockchain",
  "Polkadot",
  "Web3",
  "Wagmi",
  "RainbowKit",
  "Auth0",
  "Clerk",
  "JWT",
  "Razorpay",
  "Cloudinary",
  "OpenAI",
  "AI",
  "Jest",
  "Git",
  "GitHub",
  "Docker",
  "Linux",
  "Postman",
  "Figma",
  "AWS",
  "AWS EC2",
  "Azure",
  "Vercel",
] as const;
